# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1535f9a03187d5185f5ccf636a1d792f39aa6dc6661ba9b3b9cc3becaad7eab759539cd8bfd9a1583bca5eceeb3a4c329218d5b1f59582cc14949f1fd112e0c

test:
  secret_key_base: ef06e04713af0f91b2bcacc81619f8bf650b0ba69c09ce156fc9400e061b990ff52d08e89a49cba8e0c9812037f6a0623c1c6ce71157c589c5e48d6340e24a01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
